import './global.css'; // Ensure correct import path
//import { Roboto, Inter } from 'next/font/google'; // Import Google Fonts

/*
// Initialize the fonts
const roboto = Roboto({ subsets: ['latin'], variable: '--font-roboto' });
const inter = Inter({ subsets: ['latin'], variable: '--font-inter' });
*/
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        {children}
      </body>
    </html>
  );
}
